@echo off
chcp 65001 >nul

echo ================================================
echo  DVB-T2 Setup
echo ================================================
echo.

:: Set variables
set CONFIG_FILE=conf.cfg
set RADIOCONDA_PATH=
set FFMPEG_PATH=
set OBS_STUDIO_PATH=
set DVB_RATE_PATH=
set CONDA_BASE=

echo Step 1: Searching for RadioConda/GNU Radio...

:: Check common locations
if exist "%USERPROFILE%\radioconda\python.exe" (
    set RADIOCONDA_PATH=%USERPROFILE%\radioconda\python.exe
    set CONDA_BASE=%USERPROFILE%\radioconda
    echo Found: %RADIOCONDA_PATH%
    goto found_python
)

if exist "C:\radioconda\python.exe" (
    set RADIOCONDA_PATH=C:\radioconda\python.exe
    set CONDA_BASE=C:\radioconda
    echo Found: %RADIOCONDA_PATH%
    goto found_python
)

echo Not found. Using default: C:\Users\MateBook\radioconda\python.exe
set RADIOCONDA_PATH=C:\Users\MateBook\radioconda\python.exe
set CONDA_BASE=C:\Users\MateBook\radioconda

:found_python
echo.

echo Step 2: Searching for FFmpeg...

if exist "ffmpeg.exe" (
    set FFMPEG_PATH=ffmpeg.exe
    echo Found: %FFMPEG_PATH%
    goto found_ffmpeg
)

if exist "bin\ffmpeg.exe" (
    set FFMPEG_PATH=bin\ffmpeg.exe
    echo Found: %FFMPEG_PATH%
    goto found_ffmpeg
)

echo Not found. Will use: ffmpeg.exe
set FFMPEG_PATH=ffmpeg.exe

:found_ffmpeg
echo.

echo Step 3: Searching for OBS Studio...

if exist "%PROGRAMFILES%\obs-studio\bin\64bit\obs64.exe" (
    set OBS_STUDIO_PATH=%PROGRAMFILES%\obs-studio\bin\64bit\obs64.exe
    echo Found: %OBS_STUDIO_PATH%
    goto found_obs
)

if exist "%PROGRAMFILES(x86)%\obs-studio\bin\32bit\obs32.exe" (
    set OBS_STUDIO_PATH=%PROGRAMFILES(x86)%\obs-studio\bin\32bit\obs32.exe
    echo Found: %OBS_STUDIO_PATH%
    goto found_obs
)

echo Not found. Will use default.
set OBS_STUDIO_PATH=C:\Program Files\obs-studio\bin\64bit\obs64.exe

:found_obs
echo.

echo Step 4: Searching for dvbt2rate.exe...

if exist "dvbt2rate.exe" (
    set DVB_RATE_PATH=dvbt2rate.exe
    echo Found: %DVB_RATE_PATH%
    goto found_dvbrate
)

echo Not found. Will use: dvbt2rate.exe
set DVB_RATE_PATH=dvbt2rate.exe

:found_dvbrate
echo.

echo Step 5: Creating configuration file...

echo # DVB-T2 Configuration > %CONFIG_FILE%
echo # Generated by setup.bat >> %CONFIG_FILE%
echo. >> %CONFIG_FILE%
echo RADIOCONDA_PATH=%RADIOCONDA_PATH% >> %CONFIG_FILE%
echo CONDA_BASE=%CONDA_BASE% >> %CONFIG_FILE%
echo FFMPEG_PATH=%FFMPEG_PATH% >> %CONFIG_FILE%
echo OBS_STUDIO_PATH=%OBS_STUDIO_PATH% >> %CONFIG_FILE%
echo DVB_RATE_PATH=%DVB_RATE_PATH% >> %CONFIG_FILE%

echo Configuration saved to %CONFIG_FILE%
echo.

echo Step 6: Installing Python dependencies...

if exist "%RADIOCONDA_PATH%" (
    echo Installing psutil, pillow, pywin32, pyzmq...
    "%RADIOCONDA_PATH%" -m pip install psutil pillow pywin32 pyzmq --quiet
    if errorlevel 0 (
        echo Dependencies installed successfully.
    ) else (
        echo Failed to install dependencies.
    )
) else (
    echo Python not found, skipping dependency installation.
)

echo.
echo ================================================
echo  Setup Complete!
echo ================================================
echo.
echo Edit %CONFIG_FILE% if paths are incorrect.
echo Then run start.bat to launch the application.
echo.
pause